// リンクの型定義
export interface Link {
    url: string;
    name: string;
}

// リンク集データ
const oosakaList: Link[] = [{ url: 'http://www.cqb-buddy.com/', name: 'CQB FIELD BUDDY' }];

const othersList: Link[] = [
    { url: 'https://www.militaryblog.jp/', name: 'ミリタリーブログ' },
    { url: 'https://vtg.jp/', name: 'Volk Tactical Gear' },
    { url: 'https://www.web-command.com/', name: 'WEB COMMAND' },
    { url: 'https://www.airgun.jp/', name: 'エアガンJP' },
    { url: 'https://www.heckler-koch.com/en', name: 'HK' },
    { url: 'https://hk-usa.com/', name: 'HK(USA版)' },
    { url: 'https://magpul.com/', name: 'MAGPUL INDUSTRIES' },
    { url: 'https://worldoftroy.com/', name: 'TROY INDUSTRIES' },
    { url: 'https://noveske.com/', name: 'Noveske' },
    { url: 'https://fnherstal.com/en/', name: 'FN' },
    { url: 'https://eagleindustries.com/', name: 'EAGLE' },
    { url: 'https://www.blackhawk.com/', name: 'BLACKHAWK' },
    { url: 'https://www.sightron.co.jp/', name: 'サイトロンジャパン' },
    { url: 'https://511tactical.jp/', name: '5.11 Tactical' },
    { url: 'https://www.oakley.com/ja-jp', name: 'OAKLEY' },
    { url: 'https://wileyx.jp/', name: 'Wiley X' },
    { url: 'https://surefire.jp/', name: 'sure fire' },
];

const makerList: Link[] = [
    { url: 'http://www.systema-engineering.com/', name: 'SYSTEMA' },
    { url: 'https://www.tokyo-marui.co.jp/', name: '東京マルイ' },
    { url: 'https://ksc-guns.co.jp/', name: 'KSC' },
    { url: 'https://www.wa-gunnet.co.jp/', name: 'ウエスタンアームズ' },
    { url: 'https://top-airsoft.co.jp/', name: 'TOP' },
    { url: 'https://www.s2s.co.jp/', name: 'SⅡS' },
    { url: 'https://maruzen-aps.com/', name: 'マルゼン' },
    { url: 'http://marushin-kk.co.jp/', name: 'マルシン工業' },
    { url: 'https://www.tanaka-works.com/', name: 'タナカワークス' },
    { url: 'http://www.taniokoba.co.jp/', name: 'タニオコバ' },
    { url: 'https://www.vegaforce.com/', name: 'VFC' },
    { url: 'https://www.caw.co.jp/', name: 'CAW' },
    { url: 'http://www.starairsoft.com/', name: 'STAR' },
    { url: 'https://guay2-jp.com/', name: 'G&Gアーマメント' },
    { url: 'https://www.emgjapan-ka.com/kingarms', name: 'KingArms' },
    { url: 'https://classicarmy.com/', name: 'ClassicArmy' },
    { url: 'https://www.ktw-co.com/', name: 'KTW' },
    { url: 'http://www.hartford.co.jp/', name: 'ハートフォード' },
    { url: 'http://www.crown-model.co.jp/', name: 'クラウンモデル' },
    { url: 'https://freedomart.cart.fc2.com/', name: 'フリーダム・アート' },
    { url: 'https://laylax.com/', name: 'ライラクス' },
    { url: 'http://www.intrudershop.com.tw/', name: 'ガーダー' },
    { url: 'https://novelarms.co.jp/', name: 'ノーベルアームズ' },
    { url: 'https://www.ufc-web.com/', name: 'UFC' },
    { url: 'http://www.enten.co.jp/anvil.html', name: 'Anvil' },
    { url: 'https://www.protec-ltd.com/', name: 'プロテック' },
    { url: 'https://www.lctairsoft.com/', name: 'LCT' },
    { url: 'https://www.ghkairsoft.com/', name: 'GHK' },
    { url: 'https://www.caromshot.com/', name: 'キャロムショット' },
    { url: 'https://ace-labo.com/', name: 'ACE研究所' },
    { url: 'https://madbull.com/catalog/', name: 'MADBULL' },
    { url: 'http://www.east-a-o.co.jp/', name: 'イーストA' },
    { url: 'https://www.genesis-web.jp/', name: 'ジェネシス' },
];

const shopList: Link[] = [
    { url: 'https://www.magnumshop-mugen.co.jp/', name: 'マグナムショップむげん' },
    { url: 'https://la-gunshop.com/', name: 'LAホビーショップ' },
    { url: 'https://www.phantom-web.com/', name: 'ミリタリーサープラスファントム' },
    { url: 'https://www.nakatashoten.com/', name: '中田商店' },
    { url: 'https://captaintoms.co.jp/', name: 'キャプテントム' },
    { url: 'https://aggressor-group.jp/', name: 'アグレッサーグループ' },
    { url: 'https://www.max-jp.com/4degrees/', name: '4degreesTactical' },
    { url: 'https://gunshop-tactics2.com/', name: 'ガンショップタクティクス' },
    { url: 'https://echigoya-tokyo.jp/', name: 'エチゴヤ' },
    { url: 'https://www.m514.com/', name: 'ガンショップモデルン' },
    { url: 'https://gunshop-fox.jp/', name: 'ガンショップFOX' },
    { url: 'https://orga-inc.jp/', name: 'ORGA Airsoft' },
    { url: 'https://www.super-rc.co.jp/gun/', name: 'スーパーラジコン' },
    { url: 'http://www.oceancustomtactical.com/', name: 'オーシャンカスタムタクティカル' },
    { url: 'https://repmart.jp/', name: 'レプマート' },
    { url: 'https://happoya.jp/', name: '八宝屋' },
    { url: 'https://www.samurai-gear.jp/', name: 'SAMURAI' },
    { url: 'https://chameleon-jpn.com/', name: 'カメレオン' },
    { url: 'http://optics-dealer.com/', name: 'OpticsDealer' },
    { url: 'https://tamurasoubi.co.jp/', name: '田村装備開発' },
    { url: 'https://tokyomove.ocnk.net/', name: 'MOVE' },
    { url: 'https://airgunmarket.jp/', name: 'エアガン市場' },
    { url: 'http://www.armsfactory.jp/', name: 'アームズファクトリー' },
    { url: 'https://www.mil-freaks.com/', name: 'MIL-FREAKS' },
    { url: 'https://www.41military.com/', name: '41MILITARY' },
    { url: 'https://airsoft97.com/', name: 'AIRSOFT97' },
    { url: 'https://shop.flat-airsoft.com/', name: 'HobbyBox' },
    { url: 'https://strikearms.jp/', name: 'ストライクアームズ' },
    { url: 'https://www.ranger.ne.jp/', name: 'レンジャー' },
    { url: 'https://www.hblt.jp/', name: 'HBLT' },
    { url: 'https://www.okimiri.com/', name: '沖縄ミリカジ' },
    { url: 'https://gmt-web.com/', name: 'GUN MALL TOKYO' },
    { url: 'https://frontier1.shop/', name: 'フロンティア' },
    { url: 'https://www.mokei-paddock.net/', name: 'モケイパドック' },
    { url: 'https://willy-peet-ec.com/', name: 'ウィリーピート' },
    { url: 'https://www.fortress-web.com/', name: 'フォートレス' },
    { url: 'https://www.x-fire.jp/', name: 'クロスファイア' },
    { url: 'https://angs.co.jp/', name: 'ガンショップアングス' },
    { url: 'https://www.militarygoods-jp.com/', name: 'ミリタリーグッズ.com' },
    { url: 'https://www.firstleaf-jp.com/', name: 'ファーストリーフ' },
    { url: 'https://www.lem-shop.com/', name: 'LEMサプライ' },
    { url: 'https://www.gun-shop.jp/', name: 'SYSTEM' },
    { url: 'https://hs-tamtam.co.jp/', name: 'TamTam' },
    { url: 'https://newmgc.com/', name: 'MGC' },
    { url: 'https://www.fourstar911.com/', name: 'フォースター' },
    { url: 'https://www2t.biglobe.ne.jp/~ohige/', name: 'トイガンショップクラブミッシェル' },
    { url: 'https://blackburn.jp/', name: 'ブラックバーン' },
    { url: 'https://www.rakuten.co.jp/risk/index.html', name: 'リスクコントロール' },
    { url: 'https://www.indi-nagaoka.co.jp/ecc2/', name: 'ガンショップインディ' },
    { url: 'http://www.enten.co.jp/', name: 'エンテン株式会社' },
    { url: 'https://www.tac-element.com/', name: 'TACELEMENT' },
    { url: 'http://www.revolver.shop-site.jp/index.html', name: 'Revolver' },
    { url: 'http://www.back-up-trading.com/Home200B.htm', name: 'バックアップトレーディング' },
    { url: 'https://www.world-musen.com/', name: 'ワールド無線' },
    { url: 'https://www.akaricenter.com/', name: 'アカリセンター' },
    { url: 'https://www.holkin.com/', name: 'HOLKIN' },
    { url: 'http://tokyocarol.shop-pro.jp/', name: '東京キャロル' },
    { url: 'https://www.ihagun.net/', name: 'いは軍払い下げ品店' },
    { url: 'https://www.big-out.jp/', name: 'Big-Out' },
    { url: 'https://be-max.co.jp/', name: 'Be-MAX' },
    { url: 'https://www.teduka.co.jp/', name: 'ホビーショップてづか' },
    { url: 'https://sewing.aska-corps.com/', name: '明日香縫製雑貨店' },
    { url: 'http://e-spang.net/', name: 'イースパング' },
    { url: 'https://lazycat.jp/', name: 'LAZYCAT' },
    { url: 'https://yamashita.ocnk.net/', name: '山下刃物店' },
    { url: 'https://www.pravda.jp/', name: 'プラウダ' },
    { url: 'https://pk-outlet.com/', name: 'PKウェーブ' },
    { url: 'http://www.ikariya.com/', name: 'イカリヤ' },
    { url: 'http://www.ecompany.jp/', name: 'イー・カンパニー' },
    { url: 'https://www.seabeesjp.com/', name: 'シービーズ' },
    { url: 'https://www.mash-japan.co.jp/', name: 'MASH' },
    { url: 'http://www.garage-ogawa.com/', name: 'ガレージオガワドットコム' },
    { url: 'https://gaw-airsoft.shop-pro.jp/', name: 'G.A.W.' },
];

const chibaList: Link[] = [
    { url: 'http://splash-bb.com/splashmain/', name: 'SPLASH' },
    { url: 'https://pintail.wixsite.com/bbjungle/', name: 'BB-JUNGLE' },
    { url: 'https://forest-union.jp/', name: 'フォレストユニオン' },
    { url: 'https://desert-union.jp/', name: 'デザートユニオン' },
    { url: 'https://union-base.com/', name: 'ユニオンベース' },
    { url: 'https://stadium-union.com/', name: 'UNION STADIUM' },
    { url: 'https://union-base.com/met', name: 'METユニオン' },
    { url: 'https://u-box.space/', name: 'U-BOX' },
    { url: 'https://head-shot.jp/', name: 'HEADSHOT' },
    { url: 'https://www.battle-union.jp/', name: 'バトルシティ' },
    { url: 'https://www.cimax.jp/', name: 'CIMAX' },
    { url: 'https://seals.jp/', name: 'SEALs' },
    { url: 'http://savas-m2ts.net/', name: 'SAVAS' },
    { url: 'https://village-one.org/', name: 'ビレッジワン' },
    { url: 'http://www.whitebase-sgf.com/', name: 'ホワイトベース' },
    { url: 'https://www.no9-co.jp/', name: 'No.9' },
    { url: 'https://www.ash-rockfield.com/', name: 'アッシュロックフィールド' },
];

const tokyoList: Link[] = [
    { url: 'https://www.ibf9.com/', name: 'IBF9' },
    { url: 'https://svg-ops.jp/', name: 'OPS' },
];

const kanagawaList: Link[] = [{ url: 'https://minmori.com/', name: 'みんなの森' }];

const saitamaList: Link[] = [{ url: 'https://sites.google.com/view/survivalgamefieldsister/', name: 'SISTER' }];

const gifuList: Link[] = [{ url: 'https://hqt.jp/', name: 'HQトラッド' }];

export function useLinks() {
    return {
        makerList,
        shopList,
        othersList,
        chibaList,
        tokyoList,
        kanagawaList,
        saitamaList,
        gifuList,
        oosakaList,
    };
}
